#PlotFour
unzip ("exdata-data-household_power_consumption.zip")
powercon <- read.csv("household_power_consumption.txt", sep=";")
powercon$Global_reactive_power <- as.numeric(as.character(powercon$Global_reactive_power))
powercon$Global_active_power <- as.numeric(as.character(powercon$Global_active_power))
powercon$Voltage <- as.numeric(as.character(powercon$Voltage))
powercon <- powercon[powercon$Date %in% c("1/2/2007","2/2/2007") ,]
Date2 <- as.character(powercon$Date)
Date3 <- Date3 <- dmy(Date2)
Time2 <- as.character(powercon$Time)
Time3 <- hms(Time2)
weekday <- weekdays(as.Date(powercon$Date))
powercon <- cbind(Time3, weekday, Date3, powercon)
datetime <- as.POSIXct(paste(powercon$Date3, powercon$Time), format = "%Y-%m-%d %H:%M:%S")
powercon <- cbind(datetime, powercon)

par(mfrow=c(2,2))
plot(powercon$datetime,powercon$Global_active_power,type="l", ylab="Global Active Power", xlab="")
plot(powercon$datetime,powercon$Voltage,type="l", xlab="datetime", ylab="Voltage")
plot(powercon$datetime,powercon$Sub_metering_1,type="l", ylim=c(0,40), col="black", ylab="Energy sub metering", xlab="")
par(new=T)
powercon$Sub_metering_2 <- as.numeric(levels(powercon$Sub_metering_2)[powercon$Sub_metering_2])
plot(powercon$datetime,powercon$Sub_metering_2,type="l", ylim=c(0,40), col="red", ylab="Energy sub metering", xlab="")
par(new=T)
plot(powercon$datetime,powercon$Sub_metering_3,type="l", ylim=c(0,40), col="blue",  ylab="Energy sub metering", xlab="")
plot(powercon$datetime, powercon$Global_reactive_power,type="l", xlab="datetime", ylab="Global_reactive_power")
